#
# Module manifest for module 'EnvironmentVariableItems'
#
# Generated by: Mike Flynn
#
# Generated on: 26/02/2021
#

@{

RootModule = 'EnvironmentVariableItems.psm1'

ModuleVersion = '2.0.0'

GUID = 'f5ed8644-7f61-49cb-b4e5-fe24e5e85262'

Author = 'Mike Flynn'

CompanyName = 'a1publishing.com'

Copyright = '(c) Mike Flynn. All rights reserved.'

Description = 'Module with cmdlets to easily add or remove items from `''collection type`'' Windows environment variables.  For example, adding `''C:\foo`'' to `$env:Path.'

PowerShellVersion = '5.0'

FunctionsToExport = @('Add-EnvironmentVariableItem', 'Get-EnvironmentVariableItems', 'Remove-EnvironmentVariableItem', 'Show-EnvironmentVariableItems')

CmdletsToExport = @()

VariablesToExport = @()

AliasesToExport = @('aevi', 'gevis', 'revi', 'sevis')

PrivateData = @{

    PSData = @{

        Tags = @('environment', 'variable', 'EnvironmentVariable', 'Windows', 'path', 'scope', 'item', 'split')

        LicenseUri = 'https://github.com/a1publishing/Powershell_Module_EnvironmentVariableItems/blob/master/LICENSE'

        ProjectUri = 'https://github.com/a1publishing/Powershell_Module_EnvironmentVariableItems'

        ReleaseNotes = '2.0.0: Replaced SupportsShouldProcess confirmation with -NoConfirmationRequired switch (breaking: -WhatIf and -Confirm no longer supported); refactored internals to use PowerShell class (requires PS 5.0+)'

    }

}

}
