#
# Module manifest for module 'EnvironmentVariableItems'
#
# Generated by: Mike Flynn
#
# Generated on: 26/02/2021
#

@{

RootModule = 'EnvironmentVariableItems.psm1'

ModuleVersion = '2.3.1'

GUID = 'f5ed8644-7f61-49cb-b4e5-fe24e5e85262'

Author = 'Mike Flynn'

CompanyName = 'a1publishing.com'

Copyright = '(c) Mike Flynn. All rights reserved.'

Description = 'Module with cmdlets to easily add or remove items from `''collection type`'' Windows environment variables.  For example, adding `''C:\foo`'' to `$env:Path.'

PowerShellVersion = '5.0'

FunctionsToExport = @('Add-EnvironmentVariableItem', 'Get-EnvironmentVariableItems', 'Remove-EnvironmentVariableItem', 'Show-EnvironmentVariableItems')

CmdletsToExport = @()

VariablesToExport = @()

AliasesToExport = @('aevi', 'gevis', 'revi', 'sevis')

PrivateData = @{

    PSData = @{

        Tags = @('environment', 'variable', 'EnvironmentVariable', 'Windows', 'path', 'scope', 'item', 'split')

        LicenseUri = 'https://github.com/a1publishing/Powershell_Module_EnvironmentVariableItems/blob/master/LICENSE'

        ProjectUri = 'https://github.com/a1publishing/Powershell_Module_EnvironmentVariableItems'

        ReleaseNotes = '
2.1.0: Multi-scope support — ProcessAndMachine/pam and ProcessAndUser/pau update two scopes in one command.
       Default scope changed to ProcessAndMachine.
       Breaking: -Scope Machine/User/Process renamed to MachineOnly/UserOnly/ProcessOnly.
2.2.0: Default scope reverted to ProcessOnly — safer, non-destructive default.
       Use -Scope pam/pau to persist changes across scopes.
2.2.2: Multi-scope confirmation prompt overhauled — all scope changes shown together
       with scope labels ([Process]/[Machine]/[User]) before a single confirm/cancel prompt.
2.3.0: Scope names simplified back to originals: MachineOnly->Machine, UserOnly->User, ProcessOnly->Process.
       Breaking change for users of v2.1.0-v2.2.x MachineOnly/UserOnly/ProcessOnly values.
2.3.1: Suppress current/new value output when -NoConfirmationRequired is set; only the result object is shown.
'

    }

}

}
